// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iioynkadzxzomzbjqodv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlpb3lua2Fkenh6b216Ympxb2R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MTg3OTUsImV4cCI6MjA3MTQ5NDc5NX0.NRDpZ9or2_SaOYOuE9Gc1EL_av6F8QAMqCHUHaOQwLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});